### ISSUE TITLE
cross_validation in learning.py

### ISSUE THREAD

**Issue by vinayak-tyagi** [aimacode/aima-python#1046]
Hello sir, 

I am new to this code and i was trying to read/understand this code(learing.py) 
and i found something it may be my misunderstanding if it is so i apologies  

I was reading ur learing.py code cross_validation function i found the same function(cross_validation function) is called inside same function(cross_validation function) 
Line 1066 inside 1056
would u plzzz explain ???

Screenshort
![image](https://user-images.githubusercontent.com/39195953/54470057-c921a480-47c7-11e9-9663-e45ecf16badc.png)

**Comment by sagar-sehgal** [comment]
@vinayak-tyagi The main `cross_validation` function is in the `else` part. When we have more than 1 `trials`, then the `cross_validation` function is called `trial` number of times and the average value received is returned.

**Comment by BJWiley233** [comment]
This confusion is probably due to it may have been before user posted and is currently being called inside the trials loop [here](https://github.com/aimacode/aima-python/blob/master/learning.py#L290) with `trials` by itself instead of how it reads above with `trials=1` inside the loop.  Basically this would never end cause it would decisively keep going into for loop if trials is passed as greater than 1 to the wrapper or cross_validation function.
