### ISSUE TITLE
Publish the package on PyPI

### ISSUE THREAD

**Issue by MircoT** [aimacode/aima-python#105]
To expose the package online is necessary register it on PyPI index. Here the official documentation and a useful link:

- [https://wiki.python.org/moin/CheeseShopTutorial#Submitting_Packages_to_the_Package_Index](https://wiki.python.org/moin/CheeseShopTutorial#Submitting_Packages_to_the_Package_Index)
- [http://peterdowns.com/posts/first-time-with-pypi.html](http://peterdowns.com/posts/first-time-with-pypi.html)

Otherwise it will be impossible install it via **pip**.

So the **setup.py** file have to be completed with some fields and we have to figure out the new resources to add to the **MANIFEST.in**, because it will be necessary for example include the *Jupyter notebooks* along with the code of the package, or also the license.

**Comment by norvig** [comment]
Thanks, @MicroT. However, I'm still not convinced one way or the other about whether it is worth it to have a PyPI package. Here's evidence that things are too complicated: in #98 @jeff3456 created a bunch of empty notebooks with just an "import" statement, and some of those failed because of relative imports. There are already two ways for a student to get the project: the "save in Github Desktop" button and the "Download ZIP" button; I'm not convinced that adding a third way with "pip install" is a big win. I see three options:

(1) Package/relative: Fix all the relative imports, and document how to do it for others.
(2) Package/absolute: Make a package, but with empty __init__.py, and use absolute imports in files.
     I see your point that it is nice to distinguish between importing a standard Python module and 
    importing an aima module, but I also think it will be clear which is which.
(3) No package: everything in one directory, as I originally planned. 

Can we have a discussion of the merits of each approach? @reachtarunhere ? @tmrts ? @SnShine ? @darius ? Your preferences?  Thanks!

**Comment by SnShine** [comment]
In my opinion, having a PyPI package isn't gonna make this repo more accessible to many students/learners of the book. There is no much hassle when getting a package via `pip install package` or `git clone *.git`. Both are equally difficult to do in a beginner's perspective. 

The codes are easily viewable in case of `git clone` as they are downloaded in the current folder. And I think most of the learners prefer this rather than searching for source package in site-packages folder where they are installed when used `pip install`. 

But, if we have any ideas which specifically require PyPI package, we can think of making a package. And I have got the latest merge #98, all of the notebooks don't work as they can't run because of the relative imports in our package. @jeff3456 found a fix for this here ae09a56, but I don't think it is worth it to rename all of our files.

**Comment by reachtarunhere** [comment]
Personally I have a strong preference for (3). I feel the pip install will not be useful. Let us try to look at this situation from the point of a student (this is our target audience) who will use this code. So, as a student I would like to not only use the code that is provided but would like to view the code / make changes to get a better understanding. The fact that the files are in an obscure location site-packages is not helpful. So even if I know the path it becomes an extra hassle because if I make changes to the the files in site-packages the code will be broken system wide. Therefore I might be required to make a copy somewhere else (which is the same as downloading the zip).

Considering someone who is experienced with python, git etc. She would like to use a git repo and keep track of their changes.

Overall, I don't feel their are many downsides to converting to package (as git clone and zip still work ) but the idea lacks any strong merit.

**Comment by MircoT** [comment]
Regardless of the use of the package system or not, notebooks will never work with relative imports (they can't), but if the notebooks are in the main folder of the repository the import of **aimaPy** is ok (it will be like an absolute path, so *__init__.py* can be empty) and also they can be included in the package when distributing with *wheel* or *sdist* (so the source will be visible and also the notebook can be linked to the package).

For my point of view who is experienced with Python prefer the **pip** way, instead to clone a repo. All majors libraries are on PyPI for this reason and **site-package** is not an obscure location for such people (or for someone who use Python).

For a beginner obviously is better to clone the repo or extract the zip file, but this not affect the creation of the package for those who are expert with Python, neither those who wants to use the **Jupyter notebooks** from the main folder without installing the package.

Personally I have no motivation to do the package, because it will be better for all.

I propose a solution that can satisfy both problems in the pull #109, take a look on it (is a simply filter on the module __name__, to take care if is requested as a package or not).

**Comment by norvig** [comment]
@MicroT, I appreciate your work here; I've certainly gained a better understanding of packages and relative imports from examining your work, so thanks for that.

But I showed the following code to two students who are our target audience:

```
if __name__ == "aimaPy.agents":
    from . utils import *
else:
    from utils import *
```

Both students found it confusing and could not explain exactly what it was doing. I understand that an experienced Python programmer would have no trouble with this, but that's not our target audience. So I have decided that we should go with option (3), put everything back in one directory, and remove the package stuff. 

How can we most easily get back to that state?

**Comment by tmrts** [comment]
There are two ways a student might discover this repository, either through reading AIMA or searching a specific algorithm in google and finding this repository. Our focus should be on making sure every piece of code is correct and readable. 

We don't have a strong reason to make this repository a PyPI package. However, if we wan't to increase discoverability (most likely from search engines), we can create packages for each module and add concise summary of the algorithms for that package, which would be both a SEO(search engine optimization) and increase readability.

@norvig since we are also planning to develop IPython/Jupyter notebooks and visualizations, everything in one folder might become cumbersome.

**Comment by Chipe1** [comment]
Though they might not understand what exactly is happening, I think it is clear that utils is being imported. The exact procedure or path of importing might not hold much value since students are mostly going to have a look at the actual code IMO.

**Comment by norvig** [comment]
You're right @Chipe1, they understood that utils was being imported, but they were uncertain about the details. I want students to feel secure, not uncertain; they understand a simple "import utils"

@tmrts, you are correct that the main issue is making all the code readable and correct.

Also, it might be cumbersome if there are too many files, but it looks like one directory is less cumbersome than dealing with relative imports, especially because of IPython's inability to deal with relative imports.

**Comment by reachtarunhere** [comment]
@norvig One thing we can do is to move the tests to a different directory as these are for devs and not aimed towards students.

**Comment by MircoT** [comment]
@norvig to have a more clear one folder organization tests can be in a folder as @reachtarunhere said and files can have a name depends on the purpoise, for example:

```bash
aima_agents.py
aima_csp.py
[...]
aima_utils.py

note_agents.ipynb
note_csp.ipynb

# or something like
doc_agents.ipynb
[...]
```
So  there will be less confusion on what is code and what is an example of use or a documentation notebook or whatever...
