### ISSUE TITLE
Backward compatibility for Python 2

### ISSUE THREAD

**Issue by chiragvartak** [aimacode/aima-python#122]
I know that right now, we are writing code that's intended to work with Python 3.5 but do we want to maintain backward compatibility as well? I mean, do we want the code to work with both, say 2.7 and 3.5?  
If yes, the code will have to be conditional code where we consider the version of Python on the machine where the code is running. [See this.](http://python3porting.com/problems.html)  
If no, then, well, no problems!

**Comment by Chipe1** [comment]
I think such code would be too ugly to read. There is a aima3python2 branch if that's what you are looking for.

**Comment by chiragvartak** [comment]
Agreed, it would be ugly. But not that much.  
Also, think about it. Many students still use Python 2. We wouldn't want to discourage them from using this repo. aima3python2 exists, but the branch intended to be used and developed further is the master branch.  
I don't mind working entirely in Python 3. As a developer, it's easier for me to do so. Just asking this question to confirm what our protocol should be. In any case, this will be up to the repo owners to decide.

**Comment by norvig** [comment]
Good question, @chiragvartak! I asked several Python experts if I should aim for that, and the consensus was no. As @Chipe1 says, it would make the code more ugly. It would also complicate testing, although we could automate that. 

The main factor was that since we can assume that anyone using this project is a programmer, not just a naive user, it shouldn't be hard for them to install Python 3. Maybe in the README or somewhere I should mention how to get Python 3, and how to run code online in the browser if you can't install on some machine.

**Comment by chiragvartak** [comment]
Alright, it's settled then.
