### ISSUE TITLE
flake8 warnings in modules

### ISSUE THREAD

**Issue by chiragvartak** [aimacode/aima-python#139]
We use [flake8](http://dancallahan.info/journal/python-flake8/) to make the code in this repository to be compliant with [PEP8 guidelines](https://www.python.org/dev/peps/pep-0008/). The flake8 warnings can be can be viewed in the [latest Travis build](https://travis-ci.org/aimacode/aima-python).  
Look for the line beginning with `$ flake8` and expand it to view the warnings.

**Comment by Chipe1** [comment]
I feel that code can be clear and easy to grasp without having to pass pep8 tests. Things like exactly 2 blank lines, use of lambda expression, max line length do not make the code illegible. Is there any way to drop those warnings

**Comment by tmrts** [comment]
@Chipe1 the problem with that is, everybody has a personal style and they use the constructs they like.
Consistency is much more important than having a few inconveniences with style.

**Comment by chiragvartak** [comment]
Yes, @tmrts, consistency has to be maintained, but @Chipe1 has a point too. There might arise cases where being too determined to stick with PEP8 guidelines might interfere with code readability. In these cases, I suggest we shouldn't ignore our common sense and do the best to maintain this code readability. [Straight from the PEP8 Style Guide.](https://www.python.org/dev/peps/pep-0008/#a-foolish-consistency-is-the-hobgoblin-of-little-minds)  
But I feel it is a good idea to stick to the guidelines mostly and diverge from them only when necessary.

**Comment by chiragvartak** [comment]
And oh yes, [this is how you drop the warnings](https://flake8.readthedocs.org/en/latest/) if you wish to.  
@Chipe1

**Comment by norvig** [comment]
I'm sympathetic with @Chipe1. For example, I prefer 1 blank line between functions, because I prefer functions that only a few lines long, and don't have any internal blank lines. But I can also see that if a reader is used to having two blank lines everywhere, then why should we be different? The `golang` community runs all their code through a pretty-printer, so everyone has exactly the same formatting; that seems to work fine. So, I'm willing to run flake8, but we shouldn't be a slave to it.  I added a couple of errors/warnings to the --ignore flag; if there are more things to ignore, we can do it there rather than with a `# noqa`.
