### ISSUE TITLE
Precedence of propositional symbols in expr() function logic.py

### ISSUE THREAD

**Issue by chiragvartak** [aimacode/aima-python#164]
Currently, in the `expr()` function in the `logic.py` module, `>>` (implies) takes a higher precedence than `&` (and). There might be undesirable precedence in other combinations of symbols as well. We wish to have the following precedence order:  

> ~  &  |  >>  %  

which, in our module, represent the propositional symbols for:  

> negation, and, or, implies, biconditional  

Solving this will require some good working knowledge of regex in Python. Anyhow, we can always use brackets to be safe, but we may sometimes be surprised when we don't use them.

**Comment by Chipe1** [comment]
I think this can be solved using stacks the way normal expressions with arithmetic operations are evaluated. Please correct me if I'm wrong.

**Comment by chiragvartak** [comment]
Well, parsing expressions is a much worked upon problem in computer science. I am sure there are many, many solutions, even advanced solutions, to this problem.

**Comment by norvig** [comment]
@chipe1, @chiragvartak you are certainly right -- we could write or import a parser. 

I chose instead to overload the infix operators, because I wanted a user to be able to right

    P & Q

at the `>>>` prompt, or in a program, rather than having to write

    parse_expression("P & Q")

So our choices are:
1. Overloaded operators, but some wrong precedence.
2. A parser, but harder to integrate strings with other code.
3. Both 1. and 2.

**Comment by chiragvartak** [comment]
Alright, I understand it now. Changing operator precedence in `expr()` will work only if we parse the expression from a string every time. This would be tedious, less intuitive and harder to work with for longer statements. I, myself, wouldn't mind putting in a few extra brackets and be able to use operator overloading. We'll have to make sure to remind the users of this though.  
My opinion, let's stick with option 1, which is our current way of doing things. If @norvig and @Chipe1 (and anyone else who is watching this issue) agree with me on this, let's close this issue.

**Comment by norvig** [comment]
OK, we'll stick with operator overloading. There are still some questions about what to overload:
- implication operators: use `>>` and `<<`, or maybe '>=' and '<='? The later have the right precedence, but the former probably look better. Or maybe don't have any operators, and instead provide functions:

    def implies(lhs, rhs): return Expr('==>', lhs, rhs)

- logical equivalence/if-and-only-if (`<=>`) and inequivalence/either-or/xor (`<=/=>`): I don't think we can reasonably overload `==` and `!=`, because we need them to have their native meaning. I think `^` for xor is reasonable, but there aren't any good choices for `<=>`; maybe `%` is best. Or no operators and just

    def equiv(lhs, rhs): return Expr('<=>', lhs, rhs)

**Comment by chiragvartak** [comment]
I think using `>>` and `<<` is better than using `>=` and `<=`. Also, I am partial to using `%` for logical equivalence. After using the module for some time these operators started coming to me quite naturally.  
Using functions will create somewhat confusing code, I feel.  
So in summary, my suggestion: Let's stick with what we have now.

**Comment by norvig** [comment]
OK, @chiragvartak.

I think that another option is more lightweight use of `Expr`. Suppose we had a function, `e`, that was like `Expr` except that it is infix rather than prefix, and knows all the alternative names for operators:

     e(A & B, '<=>', B & A)
     e(P | Q, '==>', P)

Since you would otherwise often need extra parens to get precedence right, this would only be adding an extra `e` and two extra quote characters.

**Comment by chiragvartak** [comment]
We do have such a function, it is the `expr`! It satisfies most of the requirements of the `e` function you described, with just one difference: it takes a single string. That shouldn't be much of a problem though.

**Comment by norvig** [comment]
Yes, @chiragvartak, `expr` does do most of this -- and it does more as well. The advantage of allowing it to have multiple arguments, which need not be strings, is that within a program you can do something like

     lhs = some_expr
     rhs = another_expr
     return e(lhs, '==>', rhs)

which you can't do with `expr` currently.

**Comment by norvig** [comment]
@chiragvartak and @Chipe1 I propose #182 -- what do you think?

**Comment by chiragvartak** [comment]
On a different but related note, I see a lot of attention drawn towards implementing interactivity in notebooks. Should I start working on it too? I was more focused on writing algorithms, coding tests and writing notebooks.  
Advice?

**Comment by norvig** [comment]
Interctivity in notebooks would be awesome!
