### ISSUE TITLE
Work on HITS algorithm

### ISSUE THREAD

**Issue by samousli** [aimacode/aima-python#240]
Hello, 

I implemented the HITS algorithm and wanted to ask for a review before continuing my work on it. I'm interested in your thoughts about the way it's organized and the way to handle/plug-in the datasets.

Link: https://github.com/samousli/aima-python/blob/master/nlp.py

I used the networkx library as it was already declared as a dependency.

**Comment by thundergolfer** [comment]
Oh dear! I just submitted a pull request after implementing HITS today. This is why there should be an allocation system. 

It's late now where I am but I'll look at your work tomorrow morning. It could be better than mine and I guess you could submit a pull request to change the implementation.

Cheers

**Comment by thundergolfer** [comment]
@samousli: Hey mate, quickly looked through this. I suspect your graph approach may be more intelligent than my approach, but there are a couple of issues potentially. 

1. Doesn't adhere to pseudocode as closely as it could. For example, your use of the Pages structure forces you to use `dataset.relevant(query)` rather than `relevant_pages(query)`. 
2. Uses a set number of iterations in a loop rather than a loop against `convergence`. Though it is annoying that the textbook didn't offer guidance, implementing `convergence` is just a matter of asking the question, "Is the data still changing?".

**Comment by samousli** [comment]
Hey, thanks. We can work on those issues together, I will have time to through my code tomorrow. 

Regarding the Pages structure,  if OOP code is undesirable. it's easy to refactor it to a more functional approach.
Also, about  the convergence criteria, another solution i thought of is setting an arbitrary limit to the convergence ratio of the sums of authority scores and hub scores.

Any comments and guidance is welcome. 
Cheers

**Comment by thundergolfer** [comment]
Check out the code in my in the recent pull-request. 

I think anything that works and gets close to the pseudocode is desirable, just follow that. 

I set an arbitrary limit for the convergence yeah. It's basically calculates the average change in auth,hub value for each page and if its below a certain limit ( like 0.001 ) then stop.
