### ISSUE TITLE
Contributing - where to begin?

### ISSUE THREAD

**Issue by tejaskhot** [aimacode/aima-python#258]
@norvig 
Hello,
I am interested in contributing and have read the guidelines for the same. Is there a way to know which portions are unassigned(being done by someone else) so that I start with them? If there is some priority order then it would be nice if you could tell me the same so I can work along those lines.
Thanks.

**Comment by SnShine** [comment]
Hey @tejaskhot,

Right now no one has been working on any of the tasks. Just go though opened PRs and work on something apart from them.

You can start contributing by writing some unimplemented pseudo codes from the table in readme.
Or go through some notebooks (Search, learning, probability, csp) and add/modify parts you think necessary. If you are contributing for notebooks, consider reading the chapter in the book and doing AI course (just that chapter you are contributing) in Udacity.

We will review your PR and suggest any modifications if required.

**Comment by reachtarunhere** [comment]
@tejaskhot Just a heads up I am working on the text module right now. Also check my fork for some of the changes like the the new ngram model. The probability module has also be changed so anything that depends on that will also require some changes. I will try to finish the last few changes in the probability module and commit in the main repo so that you can get a better picture. Feel free to ping me for anything related to the probability module so that I can inform you about the changes in the pipeline :)

**Comment by tejaskhot** [comment]
Sure, thanks.
