### ISSUE TITLE
using images from other websites in notebooks?

### ISSUE THREAD

**Issue by sofmonk** [aimacode/aima-python#444]
I went through some websites and found the images would aid in our notebooks. I have the following doubts:

- can we use them directly?
- should we ask for permissions?
- is there a **license** we should look for (such as open-source, MIT, etc)?
- in **previous work** how were the images managed (manually created or requested from somewhere)?

**Comment by Chipe1** [comment]
You do need to look for license before using any image. I previously created images by combining images from free-to-use sources(https://www.creativetail.com/). We need to be careful though, as I dont know if using them as supplement to the textbook would fall under commercial use. Whatever be the case, always make sure you credit the creator.

**Comment by MrDupin** [comment]
If you picked them from random websites we cannot use them.

We can though recreate the images, as long as they are not identical. For example, I made the [perceptron image](https://github.com/aimacode/aima-python/blob/master/images/perceptron.png) on my own after I took a look at images in books/online. This is perfectly fine.

**Comment by sofmonk** [comment]
Okay, I will create images then.

And what about lecture slides images such as _Lecture slides for Automated Planning Licensed under the Creative Commons Attribution-NonCommercial-ShareAlike License: http://creativecommons.org/licenses/by-nc-sa/2.0/_ ?

aimacode/aima-python is under MIT license, does that allow us to use other such works?

**Comment by sofmonk** [comment]
The [creative commons ](https://creativecommons.org/licenses/by-nc-sa/2.0/) license says:


> You are free to:
> 
>     Share — copy and redistribute the material in any medium or format
>     Adapt — remix, transform, and build upon the material
> 
>     The licensor cannot revoke these freedoms as long as you follow the license terms.
> 

I guess we can use those.

**Comment by MrDupin** [comment]
There are quite a lot of different CC licenses.

If you see something that reads "CC-0" (or something like this) you can use it 100%.

I'm not sure though if we can use "NC" (Non Commercial) licenses, since the code here is based on a commercial product.

Also, most of the time you need to give credit to the original creator.

**Comment by sofmonk** [comment]
aimacode/aima-python is under MIT license.

**Comment by MrDupin** [comment]
That is true. I can't say I am familiar with how the MIT license works though, so I can't be of much help.

**Comment by norvig** [comment]
It is a confusing area, because nobody has ever defined "commercial use." I think that our effrots here are non-commercial, because we are not charging for them, and because the purpose is educational, not to promote a brand. @MrDupin and others are right that we need to use only images that have a CC (or other) license that allows it. And, we should always give attribution, even if the author of the image does not require attribution.
