### ISSUE TITLE
3.11	Breadth-First-Search search.py

### ISSUE THREAD

**Issue by prasadwajekar** [aimacode/aima-python#467]
while executing the code : 

SyntaxError: invalid syntax                                                                                                                    
at line 925                                                                                                                     
    print('Qu', end=' ')  \                                                                                                                     
                   ^  
second error : 
File "python", line 7, in <module>
ImportError: cannot import name 'is_in'

third error : 
Traceback (most recent call last):
  File "./prog.py", line 7, in <module>
ImportError: No module named 'utils'

**Comment by Chipe1** [comment]
I'm not sure which file you are running when you get the first error. Could you paste the contents of prog.py as it doesn't seem to be a part of the repo

**Comment by mikhail-j** [comment]
@norvig The commit ([bbcf6f6](https://github.com/aimacode/aima-python/commit/bbcf6f655f50aa1f0e553886e1f7d89ecd1fca53)) that references this issue seems to be a possible mistake. Commit bbcf6f6 went into the aima3python2 branch, but removes existing Python 2 code in favor of Python 3 code.

For example, goal_test() method for the CSP class removed the use of anonymous functions between commits.

Python 2 (commit 868982c):
```
return (len(assignment) == len(self.vars) and
            every(lambda var: self.nconflicts(var, assignment[var],
                                                                assignment) == 0,
                      self.vars))
```

Python 3 (latest commit in aima3python2 branch):
```
return (len(assignment) == len(self.variables)
            and all(self.nconflicts(variables, assignment[variables], assignment) == 0
                        for variables in self.variables))
```

The previous commit to this branch was made on Mar 2, 2016, which was a year before commit bbcf6f6.

Could you somehow revert the branch back 1 commit to maintain Python 2 usability?
