### ISSUE TITLE
Define the general open source rules this org follows

### ISSUE THREAD

**Issue by articuno12** [aimacode/aima-python#511]
Please define the open source rules this organisation follows. I can't understand why people make PRs for the things which someone implemented in some previous PR and then their PR gets merged and other just because it was old one couldn't even get reviewed.I don't think this is a healthy practice to follow. Even the PRs which make the build fails get merged.

**Comment by MrDupin** [comment]
Since I feel this is partially for me (and the Genetic Algorithm PRs), I would like to get my a word in.

Even if two PRs work on the same thing, it doesn't mean they are the same. For example, our two PRs went in different directions. I decided that the `GAState` class was not needed and didn't adhere to the pseudocode so I dropped it, while you used it more. Another difference is that I don't feel the fitness function should be in the implementation, instead leaving it to the user to define one more suitable for the problem at hand, while you implemented it into the module.

Differing opinions is a good thing in small communities like ours. My implementation is not perfect, and I can see how it would benefit from *your* PR (your `genetic_search` function can slot in beside my `genetic_algorithm`, for one). One contributor does one thing, another does another. Open source communities are built on teamwork. 

Also, code is definitely not final. Changes upon changes happen. That means we need to be adapting on the spot and communication is key. I personally received feedback for my PR from @darius and @Chipe1, which was very valuable. As contributors we have to be helping each other out, especially when the PRs pile up. I would have been more than happy to work with you if you had reached out.

Finally, as I said in your PR, @norvig took a break for a while and your PR unfortunately went unreviewed. It was bad timing and bad luck, more than anything. These things tend to happen once in a while in small communities.

**Comment by kaivalyar** [comment]
@articuno12 I think the general rules are stated quite clearly [here](https://github.com/aimacode/aima-python/blob/master/CONTRIBUTING.md#contributing-a-patch). I suppose this was a single, rare occurrence and usually there isn't such duplication of work.

As for the builds failing - in the last few weeks we have had instances where the build has broken due to a single PR - affecting all the other open PRs, but I suppose those are issues that have all been resolved now. As an organisation, aimacode has had to evaluate what tests to run, whether styling issues should break the build or not, etc and this is what was causing the build to break repeatedly. I think we can all safely assume that these issues are largely resolved now, and there is consensus among the contributors about it.

While I may be wrong about this particular instance, I do think that there are times when old PRs develop merge conflicts as a result of newer, unrelated PRs getting merged. This is not a case of duplication of work, and shouldn't be a great cause for concern. I would think that the only course of action in such a case is to simply resolve the merge conflicts - trying to preserve as many different contributions as possible. This is a problem that can arise regardless of the order in which PRs are merged, and is thus something I think we should all learn and accept without worry as contributors to an open source project.

**Comment by MrDupin** [comment]
I just want to note to @articuno12 that the work is not duplication. All three PRs worked on the same implementation, but with different approaches. Your PR, therefore, should not be discarded. If you resolve conflicts, there are parts that are needed (namely, your `genetic_search`).

**Comment by norvig** [comment]
I apologize for being unavailable while this was playing out. I agree with @MrDupin comments. There are three issues:

1) The build is rather fragile, and sometimes breaks for unimportant reasons. But rejecting a PR until it is fixed can mean that more requests, and more conflicts can pile up; sometimes it is better to let it break to make progress, and fix it later.

2) The project is exploratory. We don;t always know the right direction to take, so it can take some back-and-forth to get things right.

3) I have other duties that sometimes pull me away from this project. But from now to the end of the summer, I intend to be checking in at least every other day, and hopefully closer to every day.
