### ISSUE TITLE
mdp value iteration calculation seems wrong

### ISSUE THREAD

**Issue by orsenthil** [aimacode/aima-python#513]
I am using the `mdp.GridMDP` as documented.

```
   seq_dec_environ = GridMDP([[-3, -3, -3, +100],
                              [-3, None, -3,-100],
                              [-3,  -3, -3, -3]],
                              terminals=[(0, 3), (1, 3)], gamma=0.8)

   print_table(seq_dec_environ.to_grid(mdp.value_iteration(seq_dec_environ)))
```
And he result was

```
182.49732656930627    250.0934953917249   332.93553924746084     452.266550537396
 135.4739047797976                 None   248.12890941320666   227.50075663876515
 102.6064691402491   133.68576924105906    180.1503986747119    170.6655512537616
```

* Thing to observe. It is updating the reward state values. That should not happen. This is a bug in the code too.
* The values, since it updates the reward state values (+100, -100), and goes about calculating rest, the numbers are weird. 

* The expected matrix should be as discussed in the [value iteration video](https://www.youtube.com/watch?v=glHKJ359Cnc)

```
85 89 93 100
81 None 68 -100
77 73 70 47
```

**Comment by Chipe1** [comment]
The `terminals` takes indices in a different format. The origin is the bottom left cell. Right is `(1, 0)` and Up is `(0, 1)`. The terminals which you have given in python list format would become `[(3, 2), (3, 1)]` in the expected format
Also if you wish to get the output similar to the video you need to set the value of gamma to 1(no loss). Since then implementation doesn't allow such a value, set it it `0.9999` or a similar high value

**Comment by orsenthil** [comment]
Thanks, @Chipe1 for clarification. Closing this, ticket.
