### ISSUE TITLE
LaTeX in Notebooks

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#518]
I just noticed that while locally Latex works fine (when I run the jupyter notebook), online in the GitHub window it doesn't work.

Is there something we can do?

The problematic line is in search.ipynb, in the Genetic Algorithm section:

$$ chance(i) = \dfrac{fitness(i)}{\sum\limits_{k \, in \, P}{fitness(k)}} $$

**Comment by kaivalyar** [comment]
[This](http://nbviewer.jupyter.org/github/ipython/ipython/blob/1.x/examples/notebooks/Part%205%20-%20Rich%20Display%20System.ipynb#LaTeX) link provides some alternatives to using the `$$` syntax to insert a LaTeX expression inside a notebook. I'm not sure if the default github rendering will be able to pick up on these, but we can try.

Otherwise, it may be simpler to insert (temporarily) an image or some HTML code rendering the same equation.

**Comment by MrDupin** [comment]
Latex in the [Naive Bayes section](https://github.com/aimacode/aima-python/blob/master/learning.ipynb) works fine. It seems that there is an issue with the above line. I will look into this.

**Comment by norvig** [comment]
I asked Fernando Perex about this, and he said "Github is exceedingly strict in the Javascript it allows, since any Javascript breach could compromise your actual Github account. In particular, they don't allow Mathjax to run, and instead use their own, much more limited math renderer. " 

It is certainly annoying that we have to deliver notebooks on multi-platforms (github, nbviewer, desktop for mac/windows/linux) that are not compatible. It may be that we can end up hosting them somewhere that solves these problems, but for now we'll have to do trial-and-error to discover what subset of math works everywhere.

Don't be afraid to use uglier math typesetting, as long as it works (e.g., use "x / y" instead of "\frac{x,y}".

**Comment by MrDupin** [comment]
I fixed the issue in #522. It was the `limits` keyword that broke it.
