### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#533]
I noticed that the Neural Net Test caused the build to fail. There is nothing wrong in the code, but unfortunately the algorithm is non-deterministic so there is always the chance it will fail, if we are very unlucky.

What should we do about these kinds of tests? I would like to be testing them in case we break something in the implementation, but there are times where this backfires and unluckily the build fails. Another solution I can think of is increasing the threshold for error, but this may also backfire (we make a change that makes the implementation worse, but we don't notice it because it doesn't surpass the threshold).

I think the best way to go is increase the threshold by a little (say, 0.33), at least for now.

**Comment by Chipe1** [comment]
For now we could make it so that such tests donot break the build but instead give a warning.
We would need a better solution because we have the same problem with tests for other modules like GA and random forest etc.

**Comment by norvig** [comment]
I agree with @Chipe1 -- we shouldn't have tests that can occasionally fail. Some remedies, any of which are good:
* Use random.seed('something') to get deterministic results.
* Widen the acceptance level of the test. For example, rather than insisting it get one test case right, run 100 test cases and test whether it got a certain percentage right.
* Have some way of writing a warning, rather than failing the test.

**Comment by MrDupin** [comment]
Thanks for the feedback.

I like the idea of generating a lot of random test cases and running those. I will also see about giving the random generator a seed.

**Comment by MrDupin** [comment]
#534 fixes this. I went with the seed route.

**Comment by norvig** [comment]
Thanks for #534.
