### ISSUE TITLE
Search Module path_cost

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#552]
In the `GraphProblem` class in the `search` module, we have a function (`path_cost`) that computes the cost to `b` given a node `a` and the cost so far to `a`.

```
def path_cost(self, cost_so_far, A, action, B):
    return cost_so_far + (self.graph.get(A, B) or infinity)
```

What I don't understand is why we give as input `action`. It doesn't seem to play a role in the equation, so why is it there? Is it because of pseudocode I missed, or am I missing something else?

**Comment by norvig** [comment]
You're right that in this case, the action does not play a role. But I wanted the API to include the action, because some subclass might make use of it. For example, instead of the cost just being the distance between A and B, it could depend on the action: one cost for walking between A and B, a different cost for taking the bus, etc.

**Comment by MrDupin** [comment]
Ah, that makes sense. Thanks.
