### ISSUE TITLE
Travis Failing

### ISSUE THREAD

**Issue by MrDupin** [aimacode/aima-python#643]
Is there a way to restart the build? Travis failed on a [random test](https://travis-ci.org/aimacode/aima-python) with the latest PR, quite probably because of the random element.

Only users with write access can restart the build.

**Comment by norvig** [comment]
I get
E       FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/build/aimacode/aima-python/aima-data/EN-text/gutenberg.txt'

**Comment by MrDupin** [comment]
Does this error appear in `text.ipynb`? If so, I think I fixed it in #644.

**Comment by Mordekaiser11** [comment]
Hello Guys I m working on a project that is about python and artificial intelligence. We are in charge of importing searching algorithms (such as BFS,DFS) and we encountered this problem :  

C:\Users\ASUS\AppData\Local\Programs\Python\Python37\python.exe C:/Users/ASUS/.PyCharm2019.2/config/workspace/kr_test/aima-python/tests/test_search.py
============================= test session starts =============================
platform win32 -- Python 3.7.0, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: C:\Users\ASUS\.PyCharm2019.2\config\workspace\kr_test\aima-python\tests, inifile: pytest.ini
collected 394 items

test_agents.py ................                                          [  4%]
test_agents4e.py ................                                        [  8%]
test_csp.py .........................................                    [ 18%]
test_deep_learning4e.py ....                                             [ 19%]
test_games.py ...                                                        [ 20%]
test_games4e.py ....                                                     [ 21%]
test_knowledge.py ...........                                            [ 24%]
test_learning.py ..............                                          [ 27%]
test_learning4e.py ............                                          [ 30%]
test_logic.py ......................................                     [ 40%]
test_mdp.py ......                                                       [ 41%]
test_mdp4e.py ......                                                     [ 43%]
test_nlp.py ....................                                         [ 48%]
test_nlp4e.py ............                                               [ 51%]
test_perception4e.py .F.......                                           [ 53%]
test_planning.py .....................................                   [ 63%]
test_probabilistic_learning.py .                                         [ 63%]
test_probability.py ........................                             [ 69%]
test_probability4e.py ......................                             [ 75%]
test_reinforcement_learning.py ....                                      [ 76%]
test_reinforcement_learning4e.py ....                                    [ 77%]
test_search.py ..........................                                [ 83%]
test_text.py ...............                                             [ 87%]
test_utils.py .................................................          [100%]

================================== FAILURES ===================================
_________________________ test_sum_squared_difference _________________________

    def test_sum_squared_difference():
>       image = Image.open(os.path.abspath("./images/broxrevised.png"))

test_perception4e.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

fp = 'C:\\Users\\ASUS\\.PyCharm2019.2\\config\\workspace\\kr_test\\aima-python\\tests\\images\\broxrevised.png'
mode = 'r'

    def open(fp, mode="r"):
        """
        Opens and identifies the given image file.
    
        This is a lazy operation; this function identifies the file, but
        the file remains open and the actual image data is not read from
        the file until you try to process the data (or call the
        :py:meth:`~PIL.Image.Image.load` method).  See
        :py:func:`~PIL.Image.new`. See :ref:`file-handling`.
    
        :param fp: A filename (string), pathlib.Path object or a file object.
           The file object must implement :py:meth:`~file.read`,
           :py:meth:`~file.seek`, and :py:meth:`~file.tell` methods,
           and be opened in binary mode.
        :param mode: The mode.  If given, this argument must be "r".
        :returns: An :py:class:`~PIL.Image.Image` object.
        :exception IOError: If the file cannot be found, or the image cannot be
           opened and identified.
        """
    
        if mode != "r":
            raise ValueError("bad mode %r" % mode)
    
        exclusive_fp = False
        filename = ""
        if HAS_PATHLIB and isinstance(fp, Path):
            filename = str(fp.resolve())
        elif isPath(fp):
            filename = fp
    
        if filename:
>           fp = builtins.open(filename, "rb")
E           FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ASUS\\.PyCharm2019.2\\config\\workspace\\kr_test\\aima-python\\tests\\images\\broxrevised.png'

C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py:2766: FileNotFoundError
============================== warnings summary ===============================
C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:15
  C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:15: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\google\protobuf\descriptor.py:47
  C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\google\protobuf\descriptor.py:47: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from google.protobuf.pyext import _message

C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\callbacks\callbacks.py:19
  C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\callbacks\callbacks.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

test_agents.py::test_RandomAgentProgram
  C:\Users\ASUS\.PyCharm2019.2\config\workspace\kr_test\aima-python\agents.py:92: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if program is None or not isinstance(program, collections.Callable):

test_deep_learning4e.py::test_rnn
  C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\keras\engine\training_utils.py:811: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if isinstance(loss, collections.Mapping):

test_deep_learning4e.py::test_rnn
  C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:339: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    if not isinstance(values, collections.Sequence):

test_deep_learning4e.py::test_rnn
  C:\Users\ASUS\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\framework\indexed_slices.py:424: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
    "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============ 1 failed, 393 passed, 7 warnings in 144.17s (0:02:24) ============

Process finished with exit code 0



/// if you can help me, i would be thankful for this ...  have a nice day

**Comment by antmarakis** [comment]
It looks as if the broxrevised.png image is missing. Can you make sure it is in the correct path in your system?

**Comment by Mordekaiser11** [comment]
Thank you for respoding, it's solved.
