### ISSUE TITLE
Typo Error in files: 'agents.py' and 'agents.ipynb'

### ISSUE THREAD

**Issue by Dragneel7** [aimacode/aima-python#664]
I noticed some discrepancies which are as follows :-
 
agents.py: line 302 -> actual:     "(Shouldn't need to override this." in the comments
                                   expected: "(Shouldn't need to override this.)"
agents.ipyng: "lets" should be replaced with "let's" in most of the sentences and 
                        according to the coding pattern followed in most of the code an inline comment should be 
                        separated by a single space from the code in that line:
                                 actual:      location = [0,1]# change location to a 2d value
                                 expected: location = [0,1] # change location to a 2d value
 
Can I submit a PR correcting them.
Thanks.

**Comment by MrDupin** [comment]
Yes, good catches!

**Comment by Dragneel7** [comment]
@MrDupin I will continue with my work, I wish to contribute to the code, can you suggest how I should proceed?
Thanks.

**Comment by diegorodriguezv** [comment]
Excelent @Dragneel7. First step is to read https://github.com/aimacode/aima-python/blob/master/CONTRIBUTING.md.
What I did for another typo was, as you already did, open an issue, and then create a PR with the corrected typos. It was a little difficult at first to get the commit right since my jupyter notebook viewer kept modifying the notebook with the values of the calculated cells. Please check that only the lines with the corrected typos are inserted in the commit.
When you are ready to create the PR reference the issue by number: Ex. "Fixes typos referenced in Issue #664"
Thanks for your interest. :)
