### ISSUE TITLE
Tests not updated in README.md

### ISSUE THREAD

**Issue by Dragneel7** [aimacode/aima-python#667]
Some tests such as "Model based vacuum agent", "Random vacuum agent" have been added but are not updated in the README

Expected: Update README.md

**Comment by Dragneel7** [comment]
@MrDupin Chapter2 follows Vacuum cleaner as the agent in the environment so wouldn't it be better that we include examples of vacuum agent along with the blind dog agent (though both try to convey the same)?
Please update me with the work flow on the repo and what all stuff can be added to improve the code.
Thanks.

**Comment by MrDupin** [comment]
Good catch on the missing tests! The work flow is pretty simple: Just make a PR with your fixes :). If you want to take on something bigger, write an issue first letting others know and when you are ready publish your PR.

About the vacuum cleaner/blind dog, I assume you are talking about the notebook. If so, the more examples the merrier! If though the code is identical, the vacuum cleaner example should be added more like a note after the blind dog one, instead of writing a full fledged section.

**Comment by Dragneel7** [comment]
Thanks for the help, I will update the README and another PR, should I add another PR without the previous one being merged?
Regarding adding more examples in the notebook, I'll raise a issue and ask the regarding the same there.

**Comment by MrDupin** [comment]
You can publish as many PRs as you want, just make sure there are no conflicts (ie. PRs changing the same lines) or else not all of your PRs will be merged (since you will need to take care of the conflicts first).

**Comment by Dragneel7** [comment]
@MrDupin Is there any slack channel or gitter channel where we can ask doubts and discuss?

**Comment by MrDupin** [comment]
There is a [gitter channel](https://gitter.im/aimacode/Lobby), but it is inactive. We can discuss stuff by opening issues.
